src/middlewares/schemas/userSchema.ts
src/model/userModel.ts
src/services/common.ts

added bank details to users schema

added bank details to users schema

---

src/interfaces/employmenttype.ts
src/interfaces/user.ts
src/middlewares/schemas/userSchema.ts
src/model/employmentTypeModel.ts
src/model/userModel.ts
src/services/common.ts

added employment type

---

src/controllers/loginController.ts
src/controllers/registrationController.ts
src/services/login.ts

userRole Added

---

src/interfaces/user.ts
src/middlewares/schemas/userSchema.ts
src/model/bloodGroupModel.ts
src/model/organization.ts
src/model/userModel.ts
src/services/common.ts

Added Organisation details

---

src/controllers/loginController.ts
src/controllers/registrationController.ts
src/model/userModel.ts
src/services/login.ts

applicationwalkThroughflagadded

applicationwalkThroughflagadded

---

src/constants/commonErrorMessages.ts
src/controllers/commonController.ts
src/index.ts
src/interfaces/visitorscount.ts
src/model/visitorsCountModel.ts
src/routes/commonRouter.ts
src/services/common.ts

Added new API for visitors count

Added new API for visitors count

---

src/controllers/loginController.ts
src/services/login.ts

Added first name and last name in login response

Added first name and last name in login response

---

src/controllers/registrationController.ts
src/interfaces/user.ts
src/routes/adminRoutes.ts

Make password as an optional in registerEmployeeByAdmin

Make password as an optional in registerEmployeeByAdmin

---

src/constants/recruiterErrorMessages.ts
src/controllers/recruiter/updateCompanyByRecruiterController.ts
src/routes/recruiterRoutes.ts
src/services/recruiter/updateCompanyByRecruiterService.ts

Update pool company details by recruiter

Update pool company details by recruiter

---

.env
package-lock.json
package.json
src/constants/commonErrorMessages.ts
src/controllers/common/sendContactUsMailController.ts
src/routes/commonRouter.ts
src/services/common/sendContactUsMailService.ts

Implemented send contact us email functionality

Implemented send contact us email functionality

---

src/controllers/recruiter/addCommentByRecruiterController.ts
src/services/recruiter/addCommentByRecruiterService.ts

User details are not populating while adding the new comment

User details are not populating while adding the new comment

---

src/constants/commonErrorMessages.ts
src/controllers/common/updateApplicationWalkThroughController.ts
src/routes/commonRouter.ts
src/services/common/updateAppWalkThroughService.ts

Create API to change the applicationWalkThrough flag from BE to 0

Create API to change the applicationWalkThrough flag from BE to 0

---

src/controllers/admin/getEmployeeDetailsByAdminController.ts
src/routes/adminRoutes.ts
src/services/admin/getUserDetailsByAdminService.ts

Get employee details by Admin changed from email to ID

Get employee details by Admin changed from email to ID

---

src/controllers/admin/registrationController.ts
src/util/sendRegistrationOTPEmail.ts

Add new API to send the OTP to user at the time of registration

Add new API to send the OTP to user at the time of registration

---

package-lock.json
package.json
src/controllers/admin/registrationController.ts
src/util/sendRegistrationOTPEmail.ts

email html structure is done

---

src/services/recruiter/addCommentByRecruiterService.ts
src/services/recruiter/manageRecruiterService.ts
src/services/recruiter/updateCompanyByRecruiterService.ts

Add last updated date to pool companies

Add last updated date to pool companies

---

src/controllers/common/updatePasswordController.ts
src/routes/commonRouter.ts
src/services/common/updatePasswordService.ts

Change password by user after first login

Change password by user after first login

---

src/services/common/updatePasswordService.ts

Flag changed

---

src/controllers/admin/getAllEmployeeDetailsByAdminController.ts
src/controllers/superadmin/registrationController.ts
src/index.ts
src/interfaces/user.ts
src/model/userModel.ts
src/routes/superadminRoutes.ts
src/services/admin/getAllEmployeeDetailsByAdminService.ts
src/services/common/manageCommonService.ts
src/services/superadmin/registerAdminBySuperadminService.ts

Added functionlaity for BE tickets 5, 64, 65

Added functionlaity for BE tickets 5, 64, 65

---

src/constants/registrationMessages.ts
src/controllers/superadmin/registrationController.ts
src/routes/superadminRoutes.ts
src/services/superadmin/getOrganizationBySuperAdmin.ts

Get organizations for super admin

Super admin

---

src/controllers/superAdmin/getAllEmployeesBySuperAdminController.ts
src/controllers/superAdmin/getAllOrganisationsBySuperadminController.ts
src/controllers/superadmin/registrationController.ts
src/index.ts
src/routes/superadminRoutes.ts
src/services/superAdmin/getAllEmployeesBySuperAdminService.ts
src/services/superAdmin/getAllOrganizationsBySuperadminService.ts

Fixed broken issues

---

dist/controllers/recruiter/addTalentPoolCandidateController.js
dist/controllers/recruiter/getTalentPoolCandidateDetailsController.js
dist/model/talentPoolCandidatesModel.js
dist/routes/recruiterRoutes.js
dist/services/admin/getAllEmployeeDetailsByAdminService.js
dist/services/recruiter/getTalentPoolCandidateByIdService.js
src/controllers/recruiter/addTalentPoolCandidateController.ts
src/controllers/recruiter/getTalentPoolCandidateDetailsController.ts
src/interfaces/talentpoolcandidates.ts
src/model/talentPoolCandidatesModel.ts
src/routes/recruiterRoutes.ts
src/services/admin/getAllEmployeeDetailsByAdminService.ts
src/services/recruiter/getTalentPoolCandidateByIdService.ts

API to fetch the talent pool candidate details by ID

API to fetch the talent pool candidate details by ID

---

src/routes/adminRoutes.ts
src/services/admin/getUserDetailsByAdminService.ts

https://github.com/yadagiritalada143/SRYTAL-BE/pull/157#issue-2906132633

Added address on employee deatils

---

src/constants/admin/packageMessages.ts
src/controllers/admin/updatePackageByAdminController.ts
src/interfaces/package.ts
src/routes/adminRoutes.ts
src/services/admin/updatePackageByAdminService.ts

https://github.com/yadagiritalada143/SRYTAL-BE/pull/162#issue-2915935485

updatePackageByAdmin -- PUT

---

src/constants/admin/taskMessages.ts
src/controllers/admin/addTaskToPackageByAdminController.ts
src/interfaces/task.ts
src/model/taskModel.ts
src/routes/adminRoutes.ts
src/services/admin/addTaskToPackageByAdminService.ts

https://github.com/yadagiritalada143/SRYTAL-BE/pull/163#issue-2919629461

addTaskToPackageByAdmin

---

src/constants/admin/taskMessages.ts
src/controllers/admin/updateTaskByAdminController.ts
src/routes/adminRoutes.ts
src/services/admin/updateTaskByAdminService.ts

https://github.com/yadagiritalada143/SRYTAL-BE/pull/164#issue-2927164254

Update Task Api is added

---

src/constants/admin/taskMessages.ts
src/controllers/admin/addTaskByAdminController.ts
src/controllers/admin/deleteTaskByAdminController.ts
src/interfaces/package.ts
src/interfaces/task.ts
src/model/packageModel.ts
src/model/taskModel.ts
src/routes/adminRoutes.ts
src/services/admin/addTaskByAdminService.ts
src/services/admin/addTaskToPackageByAdminService.ts
src/services/admin/deleteTaskByAdminService.ts

https://github.com/yadagiritalada143/SRYTAL-BE/pull/177#issue-2970228048

Api for delete task

---

src/controllers/admin/getAllPackagesByAdminController.ts
src/services/admin/getAllPackagesByAdminService.ts
src/services/admin/getPackageDetailsByAdminService.ts

Updated getAllPackagesBy Admin to fetch all the tasks as well

Updated getAllPackagesBy Admin API to fetch all the tasks as well

---

src/constants/admin/employeePackageMessages.ts
src/controllers/admin/deleteEmployeeTaskByAdminController.ts
src/routes/adminRoutes.ts
src/services/admin/deleteEmployeeTaskByAdminService.ts

https://github.com/yadagiritalada143/SRYTAL-BE/pull/188#issue-3106869198

API for deleting specific task from employee-packages
